media: assets

content:
  - name: site
    label: Site Settings
    path: data/site.json
    type: file
    fields:
      - name: title
        label: Site Title
        type: string
      - name: description
        label: Description
        type: text
      - name: logo
        label: Logo
        type: image

  - name: pages
    label: Pages
    type: collection
    path: data/pages
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
