media: /assets

content:
  - name: site
    label: Site Settings
    path: data/site.json
    type: file
    fields:
      - name: portal_links
        label: Portal Links
        type: object
        fields:
          - name: travel_logo
            label: Travel Logo
            type: image
          - name: travel_link
            label: Travel Link
            type: string
          - name: events_logo
            label: Events Logo
            type: image
          - name: events_link
            label: Events Link
            type: string

  - name: events
    label: Moonway Events
    path: data/events.json
    type: file
    fields:
      - name: hero_title
        label: Hero Title
        type: string
      - name: hero_text
        label: Hero Text
        type: text
      - name: hero_image
        label: Hero Background
        type: image
      - name: about
        label: About Us
        type: text
      - name: services
        label: Services
        widget: list
        fields:
          - { name: icon, label: Icon (Boxicons class), widget: string }
          - { name: color, label: Color Class, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: text, label: Description, widget: text }
      - name: gallery
        label: Gallery
        widget: list
        fields:
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Alt text, widget: string }
      - name: contact
        label: Contact Info
        type: object
        fields:
          - { name: email, label: Email, type: string }
          - { name: whatsapp, label: WhatsApp, type: string }
          - { name: instagram, label: Instagram URL, type: string }
          - { name: facebook, label: Facebook URL, type: string }
