collections:
  - name: "moonway_events"
    label: "Moonway Events Page"
    files:
      - file: "moonway-events/index.md"
        label: "Moonway Events"
        name: "moonway_events_page"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "description", widget: "text" }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Subheading", name: "subheading", widget: "string" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Background Image", name: "image", widget: "image" }

          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "body", widget: "markdown" }

          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }

          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Email", name: "email", widget: "string" }
              - { label: "WhatsApp", name: "whatsapp", widget: "string" }
              - { label: "Instagram URL", name: "instagram", widget: "string" }
              - { label: "Facebook URL", name: "facebook", widget: "string" }
